### ISSUE TITLE
Android TV?

### ISSUE THREAD

**Issue by User8395** [nikgapps/project#7]

**Comment by nikhilmenghani** [comment]
should work as it is, we don't support it for now, support will be added soon, no ETAs.

**Comment by User8395** [comment]
So if I install a package on an Android TV, the loaded apps will work as normal?

**Comment by nikgapps** [comment]
The question is whether or not they will install in the first place, can you try and confirm if they are installing? If they are, it'll be easier for me to add support.

**Comment by User8395** [comment]
I'll try this and get back to you

**Comment by nikhilmenghani** [comment]
@User8395 any update?
